package org.jopac2.jbal.subject;

import java.util.Vector;

import org.jopac2.jbal.abstractStructure.Field;

/*
670 PRECIS

Field Definition

This field is used to contain subject indexing data constructed according to the Preserved Context Index System (PRECIS).

Occurrence

Optional. Repeatable.

Indicators

Indicator 1: blank (not defined)
Indicator 2: blank (not defined)

Subfields

$b Subject Indicator Number
The Subject Indicator Number (SIN) is a fixed-length number ending in a modulus 11 check digit. It identifies uniquely the address of the subject packet on a machine readable file. Not repeatable.

$c String
The string is a sequence of subject index terms in which each term is preceded by a code which determines how it should appear in entries generated by the computer in printed indexes, COM output, card catalogues, etc. Not repeatable.

$e Reference Indicator Number
A Reference Indication Number (RIN) is a fixed-length number ending in a modulus 11 check digit which identifies the address of a term in the machine-held thesaurus used as the source of See and See also references in a printed index. Repeatable.

$z Language of Terms
A three character language code giving the language of the terms used in the string. For codes see Appendix A. Not repeatable.

Notes on Field Contents

The set of PRECIS data consisting of string and RINs is identified by the SIN and is termed a subject packet. The use of the data to generate printed index entries is dependent on specific software capable of handling the manipulation coding in accordance with a set of definite rules.

Examples

EX 1
670 ##$b0479322$c*z11030*atimber*z21030*adamage*vby*wto*z31030*atermites $e0236536$e0236551$zeng 
 */

public class Precis implements SubjectInterface {
	private Vector<Field> fields=new Vector<Field>();
	private char indicator1,indicator2;
	
/**
 * Indicator 1: blank (not defined)
 * Indicator 2: blank (not defined)
 */
	public Precis() {
		indicator1=' ';
		indicator2=' ';
	}
	
/**
 * Use null values if not applicable
 * 	
 * $b Subject Indicator Number
 * The Subject Indicator Number (SIN) is a fixed-length number ending in a modulus 11 check digit. It identifies uniquely the address of the subject packet on a machine readable file. Not repeatable.
 * 
 * $c String
 * The string is a sequence of subject index terms in which each term is preceded by a code which determines how it should appear in entries generated by the computer in printed indexes, COM output, card catalogues, etc. Not repeatable.
 * 
 * $e Reference Indicator Number
 * A Reference Indication Number (RIN) is a fixed-length number ending in a modulus 11 check digit which identifies the address of a term in the machine-held thesaurus used as the source of See and See also references in a printed index. Repeatable.
 * 
 * $z Language of Terms
 * A three character language code giving the language of the terms used in the string. For codes see Appendix A. Not repeatable.
 *  
 */
	public void setSubjectData(String subjectIndicatorNumber, String string, String referenceIndicatorNumber, String languageOfTerms) {
		setField("b",subjectIndicatorNumber);
		setField("c",string);
		setField("e",referenceIndicatorNumber);
		setField("z",languageOfTerms);
	}
	
	private void setField(String n, String c) {
		if(n!=null && c!=null && c.length()>0) fields.addElement(new Field(n,c));
	}

	public Vector<Field> getData() {
		return fields;
	}

	public char getIndicator1() {
		return indicator1;
	}

	public char getIndicator2() {
		return indicator2;
	}

	public String getTagIdentifier() {
		return "670";
	}

}
