/*
 * File:           DataTypeHandlerImpl.java
 * Date:           18 gennaio 2004  11.19
 *
 * @author  romano
 * @version generated by NetBeans XML module
 */
package org.jopac2.jbal.xmlHandlers;
/*******************************************************************************
*
*  JOpac2 (C) 2002-2007 JOpac2 project
*
*     This file is part of JOpac2. http://jopac2.sourceforge.net
*
*  JOpac2 is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  JOpac2 is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with JOpac2; if not, write to the Free Software
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*
*******************************************************************************/

/**
* @author	Romano Trampus
* @version	18/01/2004
*/
import org.xml.sax.*;
@SuppressWarnings("unchecked")
public class DataTypeHandlerImpl implements DataTypeHandler {
    
    public boolean DEBUG = false;
    private String currentName;
    private String currentDescription;
    private java.util.Vector<DataType> v;
    
    public void start_data(final Attributes meta) throws SAXException {
        currentName=null;
        currentDescription=null;
        if (DEBUG) System.err.println("start_data: " + meta);
    }
    
    
	public void end_data() throws SAXException {
        v.addElement(new DataType(currentName,currentDescription));
        if (DEBUG) System.err.println("end_data()");
    }
    
    public void handle_description(final java.lang.String data, final Attributes meta) throws SAXException {
        currentDescription=data;
        if (DEBUG) System.err.println("handle_description: " + data);
    }
    
    public void start_root(final Attributes meta) throws SAXException {
        v=new java.util.Vector();
        if (DEBUG) System.err.println("start_root: " + meta);
    }
    
    public void end_root() throws SAXException {
        if (DEBUG) System.err.println("end_root()");
    }
    
    public void handle_name(final java.lang.String data, final Attributes meta) throws SAXException {
        currentName=data;
        if (DEBUG) System.err.println("handle_name: " + data);
    }
    
    public java.util.Vector<DataType> getDataTypes() {
        return v;
    }
}

